$ErrorActionPreference = 'Stop'

$projectRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$envPath = Join-Path $projectRoot '.env.local'

Write-Host ''
Write-Host 'Playlist Pilot - Spotify yerel kurulumu' -ForegroundColor Green
Write-Host 'Bilgiler yalnızca .env.local dosyasına yazılacak ve Git tarafından izlenmeyecek.' -ForegroundColor DarkGray
Write-Host ''

$clientId = (Read-Host 'Spotify Client ID').Trim()
if ([string]::IsNullOrWhiteSpace($clientId)) {
    throw 'Client ID boş bırakılamaz.'
}

$secureSecret = Read-Host 'Spotify Client Secret (yazarken görünmez)' -AsSecureString
$secretPointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureSecret)

try {
    $clientSecret = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($secretPointer)
    if ([string]::IsNullOrWhiteSpace($clientSecret)) {
        throw 'Client Secret boş bırakılamaz.'
    }

    $encryptionBytes = New-Object byte[] 32
    $randomGenerator = [Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $randomGenerator.GetBytes($encryptionBytes)
    }
    finally {
        $randomGenerator.Dispose()
    }
    $encryptionKey = [Convert]::ToBase64String($encryptionBytes)

    $content = @(
        '# Generated by scripts/configure-local-env.ps1 - do not commit'
        "SPOTIFY_CLIENT_ID=$clientId"
        "SPOTIFY_CLIENT_SECRET=$clientSecret"
        'SPOTIFY_REDIRECT_URI=http://127.0.0.1:3000/api/auth/spotify/callback'
        "TOKEN_ENCRYPTION_KEY=$encryptionKey"
        ''
        '# Google/YouTube will be configured in the next backend phase'
        'GOOGLE_CLIENT_ID='
        'GOOGLE_CLIENT_SECRET='
        'GOOGLE_REDIRECT_URI=http://127.0.0.1:3000/api/auth/google/callback'
        'DATABASE_URL='
        ''
    )

    [IO.File]::WriteAllLines($envPath, $content, [Text.UTF8Encoding]::new($false))
}
finally {
    if ($secretPointer -ne [IntPtr]::Zero) {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($secretPointer)
    }
    $clientSecret = $null
}

Write-Host ''
Write-Host 'Kurulum tamamlandı.' -ForegroundColor Green
Write-Host "Dosya: $envPath" -ForegroundColor DarkGray
Write-Host 'Güvenlik için bu dosyayı paylaşma veya GitHub Desktop ile commit etme.' -ForegroundColor Yellow
